### ISSUE TITLE
jQuery 1.7+ dependency

### ISSUE THREAD

**Issue by andrewtf** [spellerberg/vms#1]
The Drupal 7 module throws this:
"Uncaught TypeError: undefined is not a function vms.js:28"
with anything less than jQuery 1.7. Probably the easiest thing to do would be to include a jQuery update dependency.

**Comment by halfempty** [comment]
@andrewtf Thank you. Do you have a patch? (I'm not very familiar with Drupal modules, myself)

**Comment by andrewtf** [comment]
I'm working on one! It's pretty easy to implement.

**Comment by andrewtf** [comment]
Just sent you a pull request.

**Comment by halfempty** [comment]
Merged it, thank you!

**Comment by andrewtf** [comment]
Fantastic! Thanks. :)
