### ISSUE TITLE
Missing vms.php file?

### ISSUE THREAD

**Issue by andrewtf** [spellerberg/vms#3]
The readme for the drupal7 branch indicates that you will have to edit the vms.php file to suit your museum, except there's no file by that name in the repo. It's also referenced in the main module file visitor_motivation_survey.module. While the code still works without vms.php, it will fill your Drupal logs with php warnings; I edited the module file to remove the reference to vms.php and it works fine, but I'm holding off on a pull request until it's confirmed that vms.php does or doesn't exist somewhere.

**Comment by halfempty** [comment]
@andrewtf Sorry for the delayed response-- just catching up! Yeah, that reference needs to be removed. If you submit a request, I'll merge it. Cheers

**Comment by andrewtf** [comment]
I've already removed it on my end. I've also made it so that the survey doesn't show up on the Drupal administration pages, since that's kind of silly. I'll clean it up and edit the readme and submit another pull request today.

**Comment by andrewtf** [comment]
Actually, looks like that change got merged from the last request. Closing!
